name: Build on DockerHub and Deploy to AWS

on:
  push:
    branches:
      - main

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  CGP_PRIVATE_KEY: ${{ secrets.CGP_PRIVATE_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build do Backend
      - name: Build and push Backend Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./backend/
          push: true
          tags: ${{ env.DOCKERHUB_USERNAME }}/investiga_ai-backend:latest
          dockerfile: ./backend/Dockerfile

      # Build do Frontend
      - name: Build and push Frontend Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./frontend/
          push: true
          tags: ${{ env.DOCKERHUB_USERNAME }}/investiga_ai-frontend:latest
          dockerfile: ./frontend/Dockerfile

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      - name: Set permissions for private key
        run: |
          echo "${{ env.CGP_PRIVATE_KEY }}" > private-key.pem
          chmod 600 private-key.pem

      - name: Pull Backend and Frontend Docker images and Deploy
        run: |
          ssh_user=investigaaiip
          ip_address=34.44.247.78
          backend_image=${{ env.DOCKERHUB_USERNAME }}/investiga_ai-backend:latest
          backend_container=investiga_ai-backend
          frontend_image=${{ env.DOCKERHUB_USERNAME }}/investiga_ai-frontend:latest
          frontend_container=investiga_ai-frontend
          network_name=investiga_ai-network

          ssh -o StrictHostKeyChecking=no -i private-key.pem $ssh_user@$ip_address '
            # Backend
            sudo docker pull '$backend_image' &&
            sudo docker stop '$backend_container' || true &&
            sudo docker rm -f '$backend_container' || true &&
            sudo docker run --env-file .env --name '$backend_container' --network '$network_name' --restart always -d -p 8000:8010 '$backend_image'

            # Frontend
            sudo docker pull '$frontend_image' &&
            sudo docker stop '$frontend_container' || true &&
            sudo docker rm -f '$frontend_container' || true &&
            sudo docker run --name '$frontend_container' --restart always -d -p 127.0.0.1:5000:80 '$frontend_image'
          '
